logging:
  handler:
    output: none
  level:
    javax.xml.bind: WARNING
    com.sun:     WARNING
    sun.net:     WARNING
    org.apache:  OFF
    net.tiny:    FINE

#
main: ${launcher.ws}, ${launcher.db}
#shutdown = ${hook}
daemon: true
executor: ${pool}
callback: ${rest.service}
pool:
  class:   net.tiny.service.PausableThreadPoolExecutor
  size:    5
  max:     10
  timeout: 3
launcher:
  ws:
    class: net.tiny.ws.Launcher
    builder:
      port: 8080
#     bind: 192.168.1.1
      backlog: 10
      stopTimeout: 1
      executor: ${pool}
      handlers: ${handler.resource}, ${handler.sys}, ${handler.rest}, ${handler.api}, ${handler.ui}
#      ssl:
#        file:       ks
#        password:   12345
#        clientAuth: false
  db:
    class: net.tiny.db.Launcher
    builder: 
#      port: 9001
#      base: /h2
#      name: h2
      changed: sa
      create:  true
      allow:   true
      batch:   true
      clear:   true
      script:  ./src/test/resources/sql/create_sequence.sql
      load:  ./src/test/resources/csv
      producer: ${jpa.producer}

handler:
  resource:
    class:     net.tiny.ws.ResourceHttpHandler
#    cacheSize: 100
    maxAge:    0
    internal:  true
    path:      /
    paths:     /:home
    filters:   ${filter.logger}, ${filter.cors}
#
  sys:
    class:   net.tiny.ws.ControllableHandler
    path:    /sys
    auth:    ${auth.simple}
    filters: ${filter.logger}
    context: ${service.context}
#
  rest:
    class:       net.tiny.ws.rs.RestfulHttpHandler
    path:        /home
    filters:     ${filter.logger}
    application: ${rest.application}
    renderer :   ${renderer.html}
    listener:    ${rest.monitor}
  api:
    class:       net.tiny.ws.rs.RestfulHttpHandler
    path:        /api
    filters:     ${filter.jpa}, ${filter.logger}
    application: ${rest.application}
    listener:    ${rest.monitor}
  ui:
    class:       net.tiny.ws.rs.RestfulHttpHandler
    path:        /ui
    filters:     ${filter.jpa}, ${filter.logger}
    application: ${rest.application}
    renderer :   ${renderer.html}
    listener:    ${rest.monitor}
#
filter:
   logger:
     class: net.tiny.ws.AccessLogger
     out:   stdout
   cors:
     class: net.tiny.ws.CorsResponseFilter
   snap:
     class: net.tiny.ws.SnapFilter
   jpa:
     class: net.tiny.dao.HttpTransactionFilter
     producer: ${jpa.producer}
#
auth:
#
  simple:
    class:    net.tiny.ws.auth.SimpleAuthenticator
    token:    DES:CAhQn4bV:HIOsSQIg
    encode:   true
    username: paas
# 'password'
    password: Piz5wX49L4MS4SYsGwEMNw==
#
rest:
  application:
    class:   net.tiny.ws.rs.RestApplication
    pattern: net.tiny.message.*, net.tiny.feature.*
    scan:    .*/classes/, .*/feature-.*[.]jar, .*/tiny-.*[.]jar, !.*/tiny-dic.*[.]jar
    loggingLevel: info
  service:   ${service.context}
#    class:   net.tiny.ws.rs.RestServiceLocator
#    listener: ${rest.monitor}
  monitor:
    class: net.tiny.ws.rs.RestServiceLocator$RestServiceMonitor
#
service:
  context:
    class: net.tiny.ws.rs.RestServiceLocator
#
jpa:
  producer:
    class: net.tiny.dao.EntityManagerProducer
    profile: local

#
renderer:
  html:
    class:   net.tiny.ws.mvc.HtmlRenderer
    prefix:  webapp
#
vcap:
  alias: vcap.services.ups-tiny.credentials
#datasource:
#  global:
#    username: ${${vcap.alias}.cf.username}
#    password: ${${vcap.alias}.cf.password}
#
res:
  editor:
    class: net.tiny.feature.web.PropertiesEditor
    path:  /opt/demo/i18n
image:
  fas:
    class:     net.tiny.feature.demo.BrandImage
    cacheSize: 100
#    maxAge: 86400   
#    path: /home/fontawesome-free-5.11.2-web